# Generated by Django 4.1.5 on 2023-02-02 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_room_options_room_participants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messages",
            options={"ordering": ["-updated", "-created"]},
        ),
    ]
